tput setaf 54
 echo "                                    ▄▄▄▄▄▄"
 echo "                                  ▄▓▀    ▓▓▓██▄▄"
 echo "                               ▄▄▓▓  ▄▄▓▀▀     ▀▓▄"
 echo "                             ▄▓▀ ▓▌ ▐▓  ▄▄█▀▓▓▄  ▓▌"
 echo "                            ▐▓▌  ▓▌ ▐▓█▀▀▀▄▄  ▀▀▓▓▌"
 echo "                             ▓▌  ▓▌ ▐▌    ▐▓▀█▄  ▀▓▄"
 echo "                              ▓▓▄ ▀▀▀▓▄  ▄▄▓  ▓▌  ▓▌"
 echo "                              ▓▌▀▀▓▄▄▄▄▓▀ ▐▓  ▓▌ ▄▓▀"
 echo "                              ▀▓▄   ▀▀  ▄▄▓▀ ▐▓▓▓▀"
 echo "                                ▀▓▄▄▄▄▓▀▀    ▓▓"
 echo "                                      ▀▓▓▓▓▓▀▀"
 echo "      ▄▄▄▓▓▄▄▄                                          ▄▄▄      ████████"
 echo "    ▄▓▓▀▀  ▀▀▓▓▄                                       ▓▓▀▓▌        ▓▓▌"
 echo "    ▓▓▌      ▐▓▓  ▓▓▄▓▓▓▓▓▄   ▄▓▓▀█▓▄   ▓▓▄▓▓▓▓▓▄     ▓▀  ▓▓▄       ▓▓▌"
 echo "    ▓▓▌      ▐▓▓  ▓▓    ▀▓▓  ▓▓▌    ▓▓  ▓▓▌   ▐▓▓    ▐▓▌   ▓▓       ▓▓▌"
 echo "    ▓▓▌      ▐▓▓  ▓▌    ▐▓▓  ▓▓▓██████  ▓▓▌   ▐▓▓   ▐▓▓▄▄▄▄▓▓▓      ▓▓▌"
 echo "    ▀▓▓▄    ▄▓▓▀  ▓▓▄   ▄▓▓  ▓▓▌    ▄▄  ▓▓▌   ▐▓▓   ▓▓▀▀▀▀▀▀▓▓▌     ▓▓▌"
 echo "      ▀▀█▓▓█▀▀    ▓▌▀████▀    ▀▀█▓██▀   ▓▓▌   ▐▓▓  ██▀       ██  ████████"
 echo "                  ▓▌                                                     "
 echo "                  ▓▌                                                     "
 tput reset
 echo
 echo "Setting up OpenAI Gym!"
 echo "Detecting dependencies"
 echo "Need to install x,y,z"
 echo "Installing A"
